在可能会出错的地方使用try...except...finally....结构捕捉错误并进行相应处理

使用logging模块记录错误信息

```python
import logging

try:
    print('try...')
    r = 10 / 0
    print('result:', r)
except ZeroDivisionError as e:
    print('except:', e)
    logging.exception(e)
else:
    print('other errer...')
finally:
    print('finally...')
print('END')
```

也可以自定义可能的错误，用raise指出
```python
def foo(s):
    n = int(s)
    if n==0:
        raise ValueError('invalid value: %s' % s)
    return 10 / n

def bar():
    try:
        foo('0')
    except ValueError as e:
        print('ValueError!')
        raise

bar()
```